### ISSUE TITLE
dump_list problem

### ISSUE THREAD

**Issue by luistung** [cloudwu/stringid#1]
iterating over slot from 0 to 0x10000 is not a good idea, since you can not expect every list consists with slots from low to high. It is the same case for freelist. Moreover it may cause a segmentation fault when calling `stringid_str` with id pointing to middle of the freelist.

**Comment by cloudwu** [comment]
It's only for debug .

**Comment by luistung** [comment]
👌

**Comment by cloudwu** [comment]
You are correct. We should find the head of each string.

`stringid_dump()` dumps the internal structure of the `stringpool` (debug use) even the data is broken (circular linked list, or example).

**Comment by luistung** [comment]
glad to help 😊

**Comment by luistung** [comment]
https://github.com/cloudwu/stringid/blob/3f9f5022c950efb396a1693bbc01a4ab9e543952/stringid.c#L380-L383
`p->header[sec] == sec` is not a sufficient condition for sec to be a head.
